name: Linters

on: push

jobs:
  checkstyle:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run checkstyle
        run: mvn --batch-mode --no-transfer-progress checkstyle:check -Dcheckstyle.config.location=checkstyle.xml

  pmd:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run PMD
        run: mvn --batch-mode --no-transfer-progress pmd:check -Dpmd.printFailingErrors=true
