name: Release

on:
  push:
    tags:
      - 'v**'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build jar
        run: mvn --batch-mode --no-transfer-progress package

      - name: Move jar
        run: Move-Item -Path target/tfmedals-*-SNAPSHOT.jar Medal-Predictor.jar

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: Medal-Predictor
          path: Medal-Predictor.jar
